gallery/urls.py
from django.urls import path

from gallery.views import ImageView, ImageList, AlbumView, AlbumList, ImageCreate

app_name = 'gallery'
urlpatterns = [
    path('', AlbumList.as_view(), name='album_list'),
    path('images/', ImageList.as_view(), name='image_list'),
    path('image/<int:pk>/<slug>', ImageView.as_view(), name='image_detail'),
    path('upload/', ImageCreate.as_view(), name='image_upload'),
    path('album/<int:pk>/<slug>/', AlbumView.as_view(), name='album_detail'),
    path('album/<int:apk>/<int:pk>/<slug>', ImageView.as_view(), name='album_image_detail')
]

przedszkole/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from przedszkole import settings
from django.views.generic.base import TemplateView
urlpatterns = [
                  path('', include('website.urls')),
                  path('admin/', admin.site.urls),
                  path('summernote/', include('django_summernote.urls')),
                  path('gallery/', include('gallery.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('kalendarz/', include('schedule.urls')),
		  path('googleb91c225602a363f5.html',TemplateView.as_view(template_name='googleb91c225602a363f5.html')),
              ] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'website.views.error_404_view'
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = "Przedszkole CMS"
admin.site.site_title = "CMS Bartosz Adamczyk"
admin.site.index_title = "Administacja treścią"

schedule/urls.py
from django.conf.urls import url
from django.views.generic.list import ListView

from schedule.feeds import CalendarICalendar, UpcomingEventsFeed
from schedule.models import Calendar
from schedule.periods import Day, Month, Week, Year
from schedule.views import (
    CalendarByPeriodsView, CalendarView, CancelOccurrenceView, CreateEventView,
    CreateOccurrenceView, DeleteEventView, EditEventView, EditOccurrenceView,
    EventView, FullCalendarView, OccurrencePreview, OccurrenceView,
    api_move_or_resize_by_code, api_occurrences, api_select_create,
)

urlpatterns = [
    url(r'^$', ListView.as_view(model=Calendar), name='calendar_list'),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_year.html'),
        name='year_calendar',
        kwargs={'period': Year}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_tri_month.html'),
        name='tri_month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_compact_month.html'),
        name='compact_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_month.html'),
        name='month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_week.html'),
        name='week_calendar',
        kwargs={'period': Week}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_day.html'),
        name='day_calendar',
        kwargs={'period': Day}),

    url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
        CalendarView.as_view(),
        name='calendar_home',
        ),
   url(r'^fullcalendar/(?P<calendar_slug>[-\w]+)/$',
        FullCalendarView.as_view(),
        name='fullcalendar'),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        CreateEventView.as_view(),
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        EditEventView.as_view(),
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        EventView.as_view(),
        name='event'),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name='delete_event'),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        OccurrenceView.as_view(),
        name='occurrence'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        EditOccurrenceView.as_view(),
        name='edit_occurrence'),

    # urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        OccurrencePreview.as_view(),
        name='occurrence_by_date'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence_by_date'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CreateOccurrenceView.as_view(),
        name='edit_occurrence_by_date'),

    # feed urls
    url(r'^feed/calendar/upcoming/(?P<calendar_id>\d+)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),

    # api urls
    url(r'^api/occurrences', api_occurrences, name='api_occurrences'),
    url(r'^api/move_or_resize/$',
        api_move_or_resize_by_code,
        name='api_move_or_resize'),
    url(r'^api/select_create/$',
        api_select_create,
        name='api_select_create'),
    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
]

gallery/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils.functional import cached_property
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit
from PIL import Image as pImage
from PIL.ExifTags import TAGS
from gallery import settings
from pathlib import Path
from datetime import datetime
import os


class Image(models.Model):

    data = models.ImageField(upload_to='images')
    data_thumbnail = ImageSpecField(source='data',
                                    processors=[ResizeToFit(
                                        height=settings.GALLERY_THUMBNAIL_SIZE * settings.GALLERY_HDPI_FACTOR)],
                                    format='JPEG',
                                    options={'quality': settings.GALLERY_RESIZE_QUALITY})
    data_preview = ImageSpecField(source='data',
                                  processors=[ResizeToFit(width=settings.GALLERY_PREVIEW_SIZE * settings.GALLERY_HDPI_FACTOR,
                                                          height=settings.GALLERY_PREVIEW_SIZE * settings.GALLERY_HDPI_FACTOR)],
                                  format='JPEG',
                                  options={'quality': settings.GALLERY_RESIZE_QUALITY})
    date_uploaded = models.DateTimeField(auto_now_add=True)

    @cached_property
    def slug(self):
        return slugify(self.title)

    @cached_property
    def exif(self):
        exif_data = {}
        self.data.open()
        with pImage.open(self.data) as img:
            if hasattr(img, '_getexif'):
                info = img._getexif()
                if not info:
                    return {}
                for tag, value in info.items():
                    decoded = TAGS.get(tag, tag)
                    exif_data[decoded] = value
                # Process some data for easy rendering in template
                exif_data['Camera'] = exif_data.get('Model', '')
                if exif_data.get('Make', '') not in exif_data['Camera']:  # Work around for Canon
                    exif_data['Camera'] = "{0} {1}".format(exif_data['Make'].title(), exif_data['Model'])
                if 'FNumber' in exif_data:
                    exif_data['Aperture'] = str(exif_data['FNumber'][0] / exif_data['FNumber'][1])
                if 'ExposureTime' in exif_data:
                    exif_data['Exposure'] = "{0}/{1}".format(exif_data['ExposureTime'][0],
                                                             exif_data['ExposureTime'][1])
        return exif_data

    @cached_property
    def date_taken(self):
        original_exif = self.exif.get('DateTimeOriginal')
        if not original_exif:
            return self.mtime
        try:
            return datetime.strptime(original_exif, "%Y:%m:%d %H:%M:%S")
        except ValueError:  # Fall back to file modification time
            return self.mtime

    @cached_property
    def mtime(self):
        return datetime.fromtimestamp(os.path.getmtime(self.data.path))

    @property
    def title(self):
        if hasattr(self, '_title'):
            return self._title
        """ Derive a title from the original filename """
        # remove extension
        filename = Path(self.data.name).with_suffix('').name
        # convert spacing characters to whitespaces
        name = filename.translate(str.maketrans('_', ' '))
        # return with first letter caps
        return name.title()

    # Temporary override for album highlights
    @title.setter
    def title(self, name):
        self._title = name

    def get_absolute_url(self):
        return reverse('gallery:image_detail', kwargs={'pk': self.pk, 'slug': self.slug})

    def __str__(self):
        return self.title


class Album(models.Model):
    title = models.CharField(max_length=250)
    images = models.ManyToManyField(Image, blank=True, related_name='image_albums')
    highlight = models.OneToOneField(Image,
                                     related_name='album_highlight',
                                     null=True, blank=True,
                                     on_delete=models.SET_NULL,
                                     )
    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['order', '-pk']

    @property
    def slug(self):
        return slugify(self.title)

    @property
    def display_highlight(self):
        # if there is no highlight but there are images in the album, use the first
        if not self.highlight and self.images.count():
            image = self.images.earliest('id')
        else:
            image = self.highlight
        if image:
            image.title = self.title  # use the album title instead of the highlight title
        return image

    def get_absolute_url(self):
        return reverse('gallery:album_detail', kwargs={'pk': self.pk, 'slug': self.slug})

    def __str__(self):
        return self.title

gallery/forms.py
from django import forms
from PIL import Image


class ImageFileInput(forms.ClearableFileInput):

    def validate(self, value):
        return super.validate(value)


class ImageCreateForm(forms.Form):
    data = forms.FileField(widget=ImageFileInput(attrs={'multiple': True}))

    def clean(self):
        """ Validate files by checking they can be opened by PIL """
        # cleaned_data = super(ImageCreateForm, self).clean()
        image_files = self.files.getlist('data')
        invalid_images = []
        for img in image_files:
            try:
                i = Image.open(img)
                i.verify()
            except (IOError, SyntaxError):
                invalid_images += [img]
        if invalid_images:
            image_names = [i._name for i in invalid_images]
            raise forms.ValidationError("Unable to add invalid images: {0}".format(image_names))

gallery/views.py
from django.views.generic import DetailView, ListView, FormView
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.staticfiles.templatetags.staticfiles import static
from gallery.models import Image, Album
from gallery.forms import ImageCreateForm
from gallery import settings


class GallerySettingsMixin(object):
    """ Apply Gallery's Settings to a view """

    def get_context_data(self, **kwargs):
        """ Make settings available the template """
        context = super(GallerySettingsMixin, self).get_context_data(**kwargs)
        context['logo_path'] = settings.GALLERY_LOGO_PATH
        context['gallery_title'] = settings.GALLERY_TITLE
        context['hdpi_factor'] = settings.GALLERY_HDPI_FACTOR
        context['image_margin'] = settings.GALLERY_IMAGE_MARGIN
        context['footer_info'] = settings.GALLERY_FOOTER_INFO
        context['footer_email'] = settings.GALLERY_FOOTER_EMAIL
        context['theme_css_path'] = static('gallery/css/themes/{}.css'.format(settings.GALLERY_THEME_COLOR))

        return context


class ImageView(GallerySettingsMixin, DetailView):
    model = Image

    def get_context_data(self, **kwargs):
        context = super(ImageView, self).get_context_data(**kwargs)
        context['album_images'] = []
        context['apk'] = self.kwargs.get('apk')

        context['next_image'] = None
        context['previous_image'] = None

        # If there is an album in the context, look up the images in it
        if context['apk']:
            context['album'] = Album.objects.get(pk=context['apk'])
            images = context['album'].images.all()
            album_images = sorted(images, key=lambda i: i.date_taken)
            context['album_images'] = album_images
            for i in range(len(album_images)):
                if self.object.pk == album_images[i].pk:
                    if i > 0:
                        context['previous_image'] = album_images[i - 1]
                    if i < len(album_images) - 1:
                        context['next_image'] = album_images[i + 1]
        else:
            # Look for albums this image appears in
            context['albums'] = self.object.image_albums.all()

        return context


class ImageList(GallerySettingsMixin, ListView):
    model = Image

    def get_queryset(self):
        # Order by newest first
        return super(ImageList, self).get_queryset().order_by('-pk')


class ImageCreate(GallerySettingsMixin, LoginRequiredMixin, FormView):
    """ Embedded drag and drop image upload"""
    login_url = '/admin/login/'
    form_class = ImageCreateForm
    template_name = 'gallery/image_upload.html'

    def form_valid(self, form):
        """ Bulk create images based on form data """
        image_data = form.files.getlist('data')
        for data in image_data:
            image = Image.objects.create(data=data)
            image.image_albums.add(form.data['apk'])
        messages.success(self.request, "Images added successfully")
        return super().form_valid(form)

    def get_success_url(self):
        next_url = self.request.POST.get('next')
        return_url = reverse('gallery:image_list')
        if next_url:
            return_url = next_url
        return return_url

    def form_invalid(self, form):
        response = super().form_invalid(form)
        next_url = self.request.POST.get('next')
        if next_url:
            # TODO: Preserve error message
            return redirect(next_url)
        else:
            return response


class AlbumView(GallerySettingsMixin, DetailView):
    model = Album

    def get_queryset(self):
        album = super(AlbumView, self).get_queryset()
        return album

    def get_context_data(self, **kwargs):
        context = super(AlbumView, self).get_context_data(**kwargs)
        images = context['album'].images.all()
        context['images'] = sorted(images, key=lambda i: i.date_taken)
        return context


class AlbumList(GallerySettingsMixin, ListView):
    model = Album
    template_name = 'gallery/album_list.html'

gallery/templates/gallery/album_detail.html
{% extends "gallery/gallery_base.html" %}
{% load staticfiles %}

{% block title %}
    {{ album.title }}
{% endblock %}

{% block header %}
    <script type="text/javascript" src="{% static 'gallery/js/image_upload.js' %}"></script>
    <script type="text/javascript" src="{% static 'gallery/js/infinite_scroll.js' %}"></script>
    {% include "gallery/partials/justify_images.html" %}
{% endblock %}

{% block bar_title %}
    <div id="title"> {{ album.title }} </div>
{% endblock %}


{% block content %}

<!--<h2>{{ album.title }}</h2>-->

{% include "gallery/partials/image_upload_form.html" %}

<div id="image_container">

    {% for image in images %}

        <a href="{% url 'gallery:album_image_detail' album.pk image.pk image.slug %}#image_{{ image.pk }}">

            {% include "gallery/partials/thumbnail.html" %}

        </a>

    {% endfor %}


    {% if not album.images.all and user.is_authenticated %}

        <div id="empty_placeholder">
            Drag images into this box to upload to the album
        </div>

    {% endif %}

</div>

{% endblock %}

gallery/templates/gallery/album_list.html
{% extends "gallery/gallery_base.html" %}
{% load staticfiles %}

{% block title %}
    {{ gallery_title }}
{% endblock %}

{% block header %}

    <script type="text/javascript" src="{% static 'gallery/js/infinite_scroll.js' %}"></script>
    {% include "gallery/partials/justify_images.html" %}

{% endblock %}

{% block bar_title %}
    <div id="title">{{ gallery_title }}</div>
{% endblock %}

{% block content %}

<div id="image_container">

{% for album in object_list %}
    <a href="{% url 'gallery:album_detail' album.pk album.slug  %}">

        {% if album.display_highlight %}
            {% with album.display_highlight as image %}
                {% include "gallery/partials/thumbnail.html" %}
            {% endwith %}
        {% else %}
            {% include "gallery/partials/thumbnail_empty.html" %}
        {% endif %}

    </a>
{% endfor %}

</div>

{% endblock %}

gallery/templates/gallery/gallery_base.html
<!doctype html>
{% load staticfiles %}

<html>
<head>

    <meta charset="utf-8">
    <meta name="theme-color" content="#000">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>{% block title %}Starcross Django Gallery{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'gallery/css/gallery_template.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'gallery/css/gallery.css' %}">
    <link rel="stylesheet" type="text/css" href="{{ theme_css_path }}">
    <style>
        .image_spacer {
            margin-right: {{ image_margin }}px;
        }
    </style>
    {% block header %}
    {% endblock %}

</head>

<body>

<div id="top_bar">

    {% if logo_path %}
        <div id="logo">
            <a href="/gallery"><img src="{% static logo_path %}" style="height: auto; max-width:100%;"></a>
        </div>
    {%  endif %}
    <div id="detail">
        {% block bar_detail %}
        {%  endblock %}
    </div>
    {% block bar_title %}
    <div id="title">{{ gallery_title }}</div>
    {% endblock %}

</div> <!-- top_bar -->

<div id="content">

    {% block content %}
    {% endblock %}

</div> <!--content-->


<div id="footer">

    <span>{{ footer_info }}</span><br>
    <span><a href="mailto:{{ footer_email }}">{{ footer_email }}</a></span>

</div> <!--footer-->

</body>

</html>

gallery/templates/gallery/image_detail.html
{% extends "gallery/gallery_base.html" %}
{% load staticfiles %}

{% block title %}
    {% if album %}{{ album.title }} - {% endif %}{{ image.title }}
{% endblock %}

{% block header %}

    <script type="text/javascript">
        {% if previous_image %}
            previous_image_url = '{% url 'gallery:album_image_detail' apk previous_image.pk previous_image.slug %}#image_{{ previous_image.pk }}';
        {% endif %}
        {% if next_image %}
            next_image_url = '{% url 'gallery:album_image_detail' apk next_image.pk next_image.slug %}#image_{{ next_image.pk }}';
        {% endif %}
    </script>
    <script type="text/javascript" src="{% static 'gallery/js/image_navigation.js' %}"></script>
    <style>
    body, html {
        height: 100%;
        overflow: hidden;
    }
    #footer {
        display: none;
    }
    #content {
        padding-bottom: 0;
        width: 100%;
    }
    </style>

{% endblock %}

{% block bar_detail %}
    {% if image.exif.Camera %}
        <img class="exif_icon" src="{% static 'gallery/images/camera.png' %}" title="Camera"/>
        {{ image.exif.Camera }}
    {% endif %}
    {% if image.exif.LensModel %}
        <img class="exif_icon" src="{% static 'gallery/images/lens.png' %}" title="Lens"/>
        {{ image.exif.LensModel }}
    {% endif %}
    {% if image.exif.FocalLengthIn35mmFilm %}
        <img class="exif_icon" src="{% static 'gallery/images/35mm.png' %}" title="Focal Length (35mm)"/>
        {{ image.exif.FocalLengthIn35mmFilm }}mm
    {% endif %}
    {% if image.exif.Aperture %}
        <img class="exif_icon" src="{% static 'gallery/images/aperture.png' %}" title="Aperture"/>
        F/{{ image.exif.Aperture }}
    {% endif %}
    {% if image.exif.Exposure %}
        <img class="exif_icon" src="{% static 'gallery/images/exposure.png' %}" title="Exposure"/>
        {{ image.exif.Exposure }}s
    {% endif %}
    {% if image.exif.ISOSpeedRatings %}
        <img class="exif_icon" src="{% static 'gallery/images/iso.png' %}" title="ISO"/>
        ISO {{ image.exif.ISOSpeedRatings }}
    {% endif %}
{% endblock %}

{% block bar_title %}
    <div id="title">
        {% if album %}
            <a href="{% url 'gallery:album_detail' apk album.slug %}">
            {{ album.title }}
            </a>
            -
        {% endif %}
        {{ image.title }}
    </div>
{% endblock %}

{% block content %}

<a href="{{ image.data.url }}">
    <img id="image_preview" src="{{ image.data_preview.url }}" alt="{{ image.title }}"/>
</a>

<div id="album_preview">
{% if album_images %}

    {% for image in album_images %}
        <a href="{% url 'gallery:album_image_detail' apk image.pk image.slug %}#image_{{ image.pk }}" style="display: inline-block;">
            {% include 'gallery/partials/thumbnail_preview.html' %}
       </a>
    {% endfor %}

{% elif albums %}

    {% for album in albums %}

        {% with album.display_highlight as image %}

        <a href="{% url 'gallery:album_detail' album.pk album.slug  %}" style="display: inline-block;">
            {% include 'gallery/partials/thumbnail_preview.html' %}
        </a>

        {% endwith %}

    {% endfor %}


{% endif %}
 </div>

{% endblock %}

gallery/templates/gallery/image_list.html
{% extends "gallery/gallery_base.html" %}
{% load staticfiles %}

{% block title %}
    {{ gallery_title }}
{% endblock %}

{% block header %}

    <script type="text/javascript" src="{% static 'gallery/js/image_upload.js' %}"></script>
    <script type="text/javascript" src="{% static 'gallery/js/infinite_scroll.js' %}"></script>
    {% include "gallery/partials/justify_images.html" %}

{% endblock %}

{% block bar_title %}
    <div id="title">{{ gallery_title }}</div>
{% endblock %}

{% block content %}

{% include "gallery/partials/image_upload_form.html" %}

<div id="image_container">

    {% for image in image_list %}

        <a href="{% url 'gallery:image_detail' image.pk image.slug %}">

            {% include "gallery/partials/thumbnail.html" %}

        </a>

    {% endfor %}


    {% if not image_list and user.is_authenticated %}

        <div id="empty_placeholder">
            Drag images into this box to upload to the image feed
        </div>

    {% endif %}

</div>

{% endblock %}

gallery/templates/gallery/image_upload.html
{% extends "gallery/gallery_base.html" %}
{% load staticfiles %}

{% block header %}

{% endblock %}

{% block content %}

<style>
    #image_upload_form {
        display: inherit;
    }
</style>

{% include "gallery/partials/image_upload_form.html" %}


{% endblock %}